"""add test_table

Revision ID: 770727dac7ad
Revises: 20260409_000001
Create Date: 2026-04-09 16:45:55.520574
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770727dac7ad'
down_revision = '20260409_000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_table_id'), 'test_table', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_table_id'), table_name='test_table')
    op.drop_table('test_table')
    # ### end Alembic commands ###
